version: '3.7'

services:
  drupal:
    image: drupal:7.63
    volumes:
      - drupal_root:/var/www/html
      - /var/www/html/modules
      - /var/www/html/profiles
      - /var/www/html/themes
      - ./Drupal/modules/custom:/var/www/html/sites/all/modules/nota
    ports:
      #- 8080:80
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:10.0.37
    environment:
      MYSQL_ROOT_PASSWORD: example
  drush:
    image: drupaldocker/drush:8-alpine
    volumes:
      - drupal_root:/var/www/html
    restart: 'no'
    depends_on:
      - drupal

volumes:
  drupal_root:
